#!/usr/bin/env bash
URL="https://codeberg.org/heretic/torrents-csv-data/raw/branch/main/torrents.csv"
FILE=~/.local/share/torrents.csv
MINSEEDERS=10

if [ ! -f $FILE ]; then
  echo "Downloading $URL to $FILE"
  curl -L "$URL" |\
    tail -n +2 |\
    numfmt -d ';' --field=3 --to=iec-i --suffix=B --padding=-7 |\
    sort -hr --field-separator=';' -k 4 |\
    awk -s 'BEGIN {FS=";";OFS=";"}  {print NR,$0}' > "$FILE"
fi

query="$@"

IFS=';' read -ra selected < <(
  awk -s 'BEGIN {FS=";";OFS=";"} $6 >= '$MINSEEDERS' {print "\033[1;33m"" "$4"\033[0m","\033[1;32m"" "$6"\t""\033[0m",$3,$1}' "$FILE" |\
  fzf -i \
    --tiebreak=index \
      --delimiter=';' \
      --query="$query" \
      --ansi \
      --height='100%' \
      --preview-window='down,wrap,4' \
      --preview="sed -n {4}p $FILE |\
      awk 'BEGIN {FS=\";\";OFS=\"\n\"} {\$1=\$1;\
      print \"\033[1m\"\"  \"\$3\"\033[0m\", \"\033[1;33m\"\"  \"\$4\"\033[0m\", \"\033[1;32m\"\"  \"\$6\"\033[0m\"}'"
)

if [ -n "${selected[3]}" ]; then
  hash=$(sed -n "${selected[3]}p" "$FILE" | cut -d ';' -f 2)
  uri=$(printf "magnet:?xt=urn:btih:$hash")
  setsid -f qbittorrent --no-splash "$uri"
fi

exit
